chore: fix primary keys validation

diff --git a/.github/workflows/lint-yaml-services.yml b/.github/workflows/lint-yaml-services.yml
--- a/.github/workflows/lint-yaml-services.yml
+++ b/.github/workflows/lint-yaml-services.yml
@@ -101,15 +101,22 @@ jobs:
           fi
 
           expected_primary_keys=("name" "enabled" "hosts" "port" "protocols" "routes" "tags")
-          for service in $($YQ_PATH -e '.services[] | keys | join(" ")' "$file"); do
-            found_keys=($service)
+          found_keys_list=$($YQ_PATH -e '.services[] | keys | join(",")' "$file")
+
+          for found_keys in $found_keys_list; do
+            IFS=',' read -ra keys_array <<< "$found_keys"
+            
+            missing_keys=()
             for key in "${expected_primary_keys[@]}"; do
-              if [[ ! " ${found_keys[@]} " =~ " ${key} " ]]; then
-                echo "Error: Missing mandatory key '$key' in 'services[]' of $file."
-                echo "Found:    $found_keys"
-                exit 1
-              fi
+              [[ ! " ${keys_array[*]} " =~ " ${key} " ]] && missing_keys+=("$key")
             done
+
+            if [[ ${#missing_keys[@]} -ne 0 ]]; then
+              echo "Error: Missing mandatory keys in 'services[]' of $file."
+              echo "Missing: ${missing_keys[*]}"
+              echo "Found:   ${keys_array[*]}"
+              exit 1
+            fi
           done
 
           while IFS= read -r route_keys; do
