chore: fixes

diff --git a/.github/workflows/lint-yaml-services.yml b/.github/workflows/lint-yaml-services.yml
--- a/.github/workflows/lint-yaml-services.yml
+++ b/.github/workflows/lint-yaml-services.yml
@@ -95,12 +95,17 @@ jobs:
 
           export YQ_PATH=${{ github.workspace }}/yq
 
-          if [[ ! -f "${{ github.workspace }}/yq" ]]; then
-            echo "Error: yq executable not found at ${{ github.workspace }}/yq"
-            exit 1
+          expected_primary_keys=("name" "enabled" "host" "port" "protocol" "routes" "tags")
+
+          if $YQ_PATH -e '.upstreams[]' "$file" &>/dev/null; then
+            if $YQ_PATH -e '.services[] | has("host")' "$file" &>/dev/null || \
+              $YQ_PATH -e '.services[] | has("port")' "$file" &>/dev/null; then
+              echo "Error: 'host' and 'port' must NOT be present in 'services[]' when 'upstreams' is defined."
+              exit 1
+            fi
+            expected_primary_keys=("name" "enabled" "protocol" "routes" "tags")
           fi
 
-          expected_primary_keys=("name" "enabled" "host" "port" "protocol" "routes" "tags")
           found_keys_list=$($YQ_PATH -e '.services[] | keys | join(",")' "$file")
 
           for found_keys in $found_keys_list; do
@@ -119,15 +124,15 @@ jobs:
             fi
           done
 
-          while IFS= read -r route_keys; do
-            IFS=',' read -ra keys_array <<< "$route_keys"
+          while IFS= read -r keys; do
+            IFS=',' read -ra keys_array <<< "$keys"
             
             last_index=-1
             for key in "${expected_primary_keys[@]}"; do
               for i in "${!keys_array[@]}"; do
                 if [[ "${keys_array[i]}" == "$key" ]]; then
                   if [[ $i -lt $last_index ]]; then
-                    echo "Error: Key order in .services[] of $FILE does not follow the expected sequence."
+                    echo "Error: Key order in .services[] of $file does not follow the expected sequence."
                     echo "Expected order: ${expected_primary_keys[*]}"
                     echo "Found order:    ${keys_array[*]}"
                     exit 1
@@ -139,10 +144,10 @@ jobs:
             done
           done < <($YQ_PATH -e '.services[] | keys | join(",")' "$file")
 
-          if [[ "$found_keys" =~ tls_verify|ca_certificates ]]; then
-            if [[ ! "$found_keys" =~ port.*tls_verify || "$found_keys" =~ port.*ca_certificates ]]; then
-              echo "Error: File $file does not follow the expected optional key order."
-              echo "Optional keys (tls_verify, ca_certificates) must come after 'port'."
+          if [[ "$found_keys" =~ (tls_verify) ]]; then
+            if [[ ! "$found_keys" =~ port.*(tls_verify) ]]; then
+              echo "Error: File $file does not follow the expected key order."
+              echo "key 'tls_verify' must come after 'port'."
               echo "Found:    $found_keys"
               exit 1
             fi
@@ -155,13 +160,13 @@ jobs:
               echo "Found:    $found_keys"
               exit 1
             fi
-          fi
 
-          if [[ ! "$found_keys" =~ plugins.*routes ]]; then
-            echo "Error: File $file does not follow the expected key order."
-            echo "Key 'plugins' must come before 'routes'."
-            echo "Found:    $found_keys"
-            exit 1
+            if [[ ! "$found_keys" =~ plugins.*routes ]]; then
+              echo "Error: File $file does not follow the expected key order."
+              echo "Key 'plugins' must come before 'routes'."
+              echo "Found:    $found_keys"
+              exit 1
+            fi
           fi
 
           expected_plugin_keys=("name" "enabled" "protocols" "config")
@@ -183,15 +188,15 @@ jobs:
             fi
           done
 
-          while IFS= read -r route_keys; do
-            IFS=',' read -ra keys_array <<< "$route_keys"
+          while IFS= read -r keys; do
+            IFS=',' read -ra keys_array <<< "$keys"
             
             last_index=-1
             for key in "${expected_plugin_keys[@]}"; do
               for i in "${!keys_array[@]}"; do
                 if [[ "${keys_array[i]}" == "$key" ]]; then
                   if [[ $i -lt $last_index ]]; then
-                    echo "Error: Key order in .services[].plugins[] of $FILE does not follow the expected sequence."
+                    echo "Error: Key order in .services[].plugins[] of $file does not follow the expected sequence."
                     echo "Expected order: ${expected_plugin_keys[*]}"
                     echo "Found order:    ${keys_array[*]}"
                     exit 1
@@ -218,7 +223,7 @@ jobs:
             exit 1
           fi
 
-          expected_route_keys=("name" "hosts" "protocols" "methods" "paths")
+          expected_route_keys=("name" "protocols" "methods" "paths")
           found_keys_list=$($YQ_PATH -e '.services[].routes[] | keys | join(",")' "$file")
 
           for found_keys in $found_keys_list; do
@@ -237,8 +242,8 @@ jobs:
             fi
           done
 
-          while IFS= read -r route_keys; do
-            IFS=',' read -ra keys_array <<< "$route_keys"
+          while IFS= read -r keys; do
+            IFS=',' read -ra keys_array <<< "$keys"
             
             last_index=-1
             for key in "${expected_route_keys[@]}"; do
@@ -256,6 +261,15 @@ jobs:
               done
             done
           done < <($YQ_PATH -e '.services[].routes[] | keys | join(",")' "$file")
+
+          if [[ "$found_keys" =~ (hosts) ]]; then
+            if [[ ! "$found_keys" =~ name.*(hosts) ]]; then
+              echo "Error: File $file does not follow the expected key order."
+              echo "key 'hosts' must come after 'name'."
+              echo "Found:    $found_keys"
+              exit 1
+            fi
+          fi
 
           expected_plugin_route_keys=("name" "enabled" "protocols" "config")
           found_keys_list=$($YQ_PATH -e '.services[].routes[].plugins[] | keys | join(",")' "$file")
@@ -276,8 +290,8 @@ jobs:
             fi
           done
 
-          while IFS= read -r route_keys; do
-            IFS=',' read -ra keys_array <<< "$route_keys"
+          while IFS= read -r keys; do
+            IFS=',' read -ra keys_array <<< "$keys"
             
             last_index=-1
             for key in "${expected_plugin_route_keys[@]}"; do
