chore: adds one more done

diff --git a/.github/workflows/lint-yaml-services.yml b/.github/workflows/lint-yaml-services.yml
--- a/.github/workflows/lint-yaml-services.yml
+++ b/.github/workflows/lint-yaml-services.yml
@@ -104,20 +104,21 @@ jobs:
           found_keys_list=$($YQ_PATH -e '.services[] | keys | join(",")' "$file")
           echo "DEBUG: found_keys_list='$found_keys_list'"
 
-          IFS=',' read -ra found_keys_array <<< "$found_keys_list"
-          for found_keys in "${found_keys_array[@]}"; do
-          
-            missing_keys=()
-            for key in "${expected_primary_keys[@]}"; do
-              [[ ! " ${keys_array[*]} " =~ " ${key} " ]] && missing_keys+=("$key")
-            done
+            for found_keys in $found_keys_list; do
+              IFS=',' read -ra keys_array <<< "$found_keys"
+              
+              missing_keys=()
+              for key in "${expected_primary_keys[@]}"; do
+                [[ ! " ${keys_array[*]} " =~ " ${key} " ]] && missing_keys+=("$key")
+              done
 
-            if [[ ${missing_keys[@]} -ne 0 ]]; then
-              echo "Error: Missing mandatory keys in 'services[]' of $file."
-              echo "Missing: ${missing_keys[*]}"
-              echo "Found:   ${keys_array[*]}"
-              exit 1
-            fi
+              if [[ ${missing_keys[@]} -ne 0 ]]; then
+                echo "Error: Missing mandatory keys in 'services[]' of $file."
+                echo "Missing: ${missing_keys[*]}"
+                echo "Found:   ${keys_array[*]}"
+                exit 1
+              fi
+            done
           done
 
           while IFS= read -r route_keys; do
