chore: updates yamllint

diff --git a/.github/workflows/lint-yaml-services.yml b/.github/workflows/lint-yaml-services.yml
--- a/.github/workflows/lint-yaml-services.yml
+++ b/.github/workflows/lint-yaml-services.yml
@@ -100,95 +100,129 @@ jobs:
             exit 1
           fi
 
-          expected_initial_keys="name enabled host port"
-          expected_end_keys="routes tags"
-          $YQ_PATH -e '.services[] | keys | join(" ")' "$file" | while read -r found_keys; do
-            if [[ ! "$found_keys" =~ ^$expected_initial_keys ]]; then
-              echo "Error: File $file does not follow the expected initial key order."
-              echo "Expected (initial): $expected_initial_keys"
-              echo "Found:              $found_keys"
-              exit 1
-            fi
-
-            if [[ "$found_keys" =~ (tls_verify|ca_certificates) ]]; then
-              if [[ ! "$found_keys" =~ port.*(tls_verify|ca_certificates) ]]; then
-                echo "Error: File $file does not follow the expected optional key order."
-                echo "Optional keys (tls_verify, ca_certificates) must come after 'port'."
-                echo "Found:    $found_keys"
+          expected_primary_keys=("name" "enabled" "hosts" "port" "protocols" "routes" "tags")
+          for service in $(yq -e '.services[] | keys | join(" ")' "$file"); do
+            found_keys=($service)
+            for key in "${expected_primary_keys[@]}"; do
+              if [[ ! " ${found_keys[@]} " =~ " ${key} " ]]; then
+                echo "Error: Missing mandatory key '$key' in 'services[]' of $file."
                 exit 1
               fi
-            fi
-
-            if [[ ! "$found_keys" =~ (protocol) ]]; then
-              echo "Error: File $file does not has the expected keys."
-              echo "Expected:  protocol"
-              echo "Found:     $found_keys"
-              exit 1
-            fi
-
-            if [[ "$found_keys" =~ (plugins) ]]; then
-              if [[ ! "$found_keys" =~ protocol.*(plugins) ]]; then
-                echo "Error: File $file does not follow the expected key order."
-                echo "key 'plugins' must come after 'protocol'."
-                echo "Found:    $found_keys"
-                exit 1
-              fi
-
-              if [[ ! "$found_keys" =~ plugins.*routes ]]; then
-                echo "Error: File $file does not follow the expected key order."
-                echo "Key 'plugins' must come before 'routes'."
-                echo "Found:    $found_keys"
-                exit 1
-              fi
-
-              expected_plugin_keys=("name" "enabled" "protocols" "config")
-              $YQ_PATH -e '.services[].plugins[] | keys | join(" ")' "$file" | while read -r plugin_keys; do
-                found_keys=($plugin_keys)
-
-                if [[ "${found_keys[*]}" != "${expected_plugin_keys[*]}" ]]; then
-                  echo "Error: Key order in plugins[] inside 'services' of $file does not follow the expected key order."
-                  echo "Expected: ${expected_plugin_keys[*]}"
-                  echo "Found:    ${found_keys[*]}"
-                  exit 1
-                fi
-              done
-
-              plugins_protocols=$($YQ_PATH eval '.services[].plugins[].protocols[]' "$file")
-              invalid_plugins_protocols=false
-
-              for protocol in $plugins_protocols; do
-                if [[ "$protocol" != "http" ]]; then
-                  invalid_plugins_protocols=true
-                  break
-                fi
-              done
-
-              if [[ "$invalid_plugins_protocols" == true ]]; then
-                echo "Error: Invalid plugins protocol inside 'services' in $file: Expected 'http' but got '$plugins_protocols'"
-                exit 1
-              fi
-            fi
-
-            if [[ ! "$found_keys" =~ $expected_end_keys$ ]]; then
-              echo "Error: File $file does not follow the expected end key order."
-              echo "Expected (end): $expected_end_keys"
-              echo "Found:          $found_keys"
-              exit 1
-            fi
+            done
           done
-
-          EXPECTED_KEYS=("name" "hosts" "protocols" "methods" "paths")
 
           while IFS= read -r route_keys; do
             found_keys=($route_keys)
             
             last_index=-1
-            for key in "${EXPECTED_KEYS[@]}"; do
+            for key in "${expected_primary_keys[@]}"; do
+              for i in "${!found_keys[@]}"; do
+                if [[ "${found_keys[i]}" == "$key" ]]; then
+                  if [[ $i -lt $last_index ]]; then
+                    echo "Error: order of mandatory keys in services[] of $file does not follow the expected sequence."
+                    echo "Expected order: ${expected_primary_keys[*]}"
+                    echo "Found order:    ${found_keys[*]}"
+                    exit 1
+                  fi
+                  last_index=$i
+                  break
+                fi
+              done
+            done
+          done < <($YQ_PATH -e '.services[] | keys | join(" ")' "$file")
+
+          if [[ "$found_keys" =~ (tls_verify|ca_certificates) ]]; then
+            if [[ ! "$found_keys" =~ port.*(tls_verify|ca_certificates) ]]; then
+              echo "Error: File $file does not follow the expected optional key order."
+              echo "Optional keys (tls_verify, ca_certificates) must come after 'port'."
+              echo "Found:    $found_keys"
+              exit 1
+            fi
+          fi
+
+          if [[ "$found_keys" =~ (plugins) ]]; then
+            if [[ ! "$found_keys" =~ protocol.*(plugins) ]]; then
+              echo "Error: File $file does not follow the expected key order."
+              echo "key 'plugins' must come after 'protocol'."
+              echo "Found:    $found_keys"
+              exit 1
+          fi
+
+          if [[ ! "$found_keys" =~ plugins.*routes ]]; then
+            echo "Error: File $file does not follow the expected key order."
+            echo "Key 'plugins' must come before 'routes'."
+            echo "Found:    $found_keys"
+            exit 1
+          fi
+
+          expected_plugin_keys=("name" "enabled" "protocols" "config")
+          for service in $(yq -e '.services[].plugins[] | keys | join(" ")' "$file"); do
+            found_keys=($service)
+            for key in "${expected_plugin_keys[@]}"; do
+              if [[ ! " ${found_keys[@]} " =~ " ${key} " ]]; then
+                echo "Error: Missing mandatory key '$key' in 'plugins[]' of $file."
+                exit 1
+              fi
+            done
+          done
+
+          while IFS= read -r route_keys; do
+            found_keys=($route_keys)
+            
+            last_index=-1
+            for key in "${expected_plugin_keys[@]}"; do
+              for i in "${!found_keys[@]}"; do
+                if [[ "${found_keys[i]}" == "$key" ]]; then
+                  if [[ $i -lt $last_index ]]; then
+                    echo "Error: order of mandatory keys in plugins[] of $file does not follow the expected sequence."
+                    echo "Expected order: ${expected_plugin_keys[*]}"
+                    echo "Found order:    ${found_keys[*]}"
+                    exit 1
+                  fi
+                  last_index=$i
+                  break
+                fi
+              done
+            done
+          done < <($YQ_PATH -e '.services[].plugins | keys | join(" ")' "$file")
+
+          plugins_protocols=$($YQ_PATH eval '.services[].plugins[].protocols[]' "$file")
+          invalid_plugins_protocols=false
+
+          for protocol in $plugins_protocols; do
+            if [[ "$protocol" != "http" ]]; then
+              invalid_plugins_protocols=true
+              break
+            fi
+          done
+
+          if [[ "$invalid_plugins_protocols" == true ]]; then
+            echo "Error: Invalid plugins protocol inside 'services' in $file: Expected 'http' but got '$plugins_protocols'"
+            exit 1
+          fi
+          done
+
+          expected_route_keys=("name" "hosts" "protocols" "methods" "paths")
+          for service in $(yq -e '.services[].routes[] | keys | join(" ")' "$file"); do
+            found_keys=($service)
+            for key in "${expected_route_keys[@]}"; do
+              if [[ ! " ${found_keys[@]} " =~ " ${key} " ]]; then
+                echo "Error: Missing mandatory key '$key' in 'routes[]' of $file."
+                exit 1
+              fi
+            done
+          done
+
+          while IFS= read -r route_keys; do
+            found_keys=($route_keys)
+            
+            last_index=-1
+            for key in "${expected_route_keys[@]}"; do
               for i in "${!found_keys[@]}"; do
                 if [[ "${found_keys[i]}" == "$key" ]]; then
                   if [[ $i -lt $last_index ]]; then
                     echo "Error: Key order in routes[] of $FILE does not follow the expected sequence."
-                    echo "Expected order: ${EXPECTED_KEYS[*]}"
+                    echo "Expected order: ${expected_route_keys[*]}"
                     echo "Found order:    ${found_keys[*]}"
                     exit 1
                   fi
@@ -200,39 +234,36 @@ jobs:
             
           done < <($YQ_PATH -e '.services[].routes[] | keys | join(" ")' "$file")
 
-          # expected_route_keys=("name" "hosts" "protocols" "methods" "paths")
-          # $YQ_PATH -e '.services[].routes[] | keys | join(" ")' "$file" | while read -r route_keys; do
-          #   found_keys=($route_keys)
-
-          #   found_required_keys=()
-          #   for key in "${expected_route_keys[@]}"; do
-          #     if [[ " ${found_keys[*]} " == *" $key "* ]]; then
-          #       found_required_keys+=("$key")
-          #     fi
-          #   done
-
-          #   found_required_keys_str="${found_required_keys[*]}"
-          #   expected_route_keys_str="${expected_route_keys[*]}"
-
-          #   if [[ "$found_required_keys_str" != "$expected_route_keys_str" ]]; then
-          #     echo "Error: Key order in routes[] of $file does not follow the expected key order."
-          #     echo "Expected: $expected_route_keys_str"
-          #     echo "Found:    $found_required_keys_str"
-          #     exit 1
-          #   fi
-          # done
-
-          expected_plugin_keys=("name" "enabled" "protocols" "config")
-          $YQ_PATH -e '.services[].routes[].plugins[] | keys | join(" ")' "$file" | while read -r plugin_keys; do
-            found_keys=($plugin_keys)
-
-            if [[ "${found_keys[*]}" != "${expected_plugin_keys[*]}" ]]; then
-              echo "Error: Key order in plugins[] inside 'routes' of $file does not follow the expected key order."
-              echo "Expected: ${expected_plugin_keys[*]}"
-              echo "Found:    ${found_keys[*]}"
-              exit 1
-            fi
+          expected_plugin_route_keys=("name" "enabled" "protocols" "config")
+          for service in $(yq -e '.services[].routes[].plugins[] | keys | join(" ")' "$file"); do
+            found_keys=($service)
+            for key in "${expected_plugin_route_keys[@]}"; do
+              if [[ ! " ${found_keys[@]} " =~ " ${key} " ]]; then
+                echo "Error: Missing mandatory key '$key' in 'services[]' of $file."
+                exit 1
+              fi
+            done
           done
+
+          while IFS= read -r route_keys; do
+            found_keys=($route_keys)
+            
+            last_index=-1
+            for key in "${expected_plugin_route_keys[@]}"; do
+              for i in "${!found_keys[@]}"; do
+                if [[ "${found_keys[i]}" == "$key" ]]; then
+                  if [[ $i -lt $last_index ]]; then
+                    echo "Error: order of mandatory keys in routes[].plugins[] of $file does not follow the expected sequence."
+                    echo "Expected order: ${expected_plugin_route_keys[*]}"
+                    echo "Found order:    ${found_keys[*]}"
+                    exit 1
+                  fi
+                  last_index=$i
+                  break
+                fi
+              done
+            done
+          done < <($YQ_PATH -e '.services[].routes[].plugins[] | keys | join(" ")' "$file"
 
           routes_protocols=$($YQ_PATH eval '.services[].routes[].protocols[]' "$file")
           invalid_routes_protocols=false
