chore: adds while loop

diff --git a/.github/workflows/lint-yaml-services.yml b/.github/workflows/lint-yaml-services.yml
--- a/.github/workflows/lint-yaml-services.yml
+++ b/.github/workflows/lint-yaml-services.yml
@@ -3,10 +3,10 @@ name: Lint YAML services
 on:
   pull_request:
     paths:
-      - "services/*/*"
+      - "services/staging/test.yml"
     branches:
       - "main"
-
+      - "feat/add-new-test-service-stg"
 env:
   YQ_VERSION: 4.45.1
   YAMLLINT_VERSION: 1.32.0
@@ -37,6 +37,9 @@ jobs:
       matrix:
         file: ${{ fromJson(needs.files_changed.outputs.files) }}
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
@@ -49,20 +52,22 @@ jobs:
           key: yq-${{ env.YQ_VERSION }}
           path: ${{ github.workspace }}/yq
           restore-keys: yq
-
+  
       - name: Download yq
         if: steps.cache-yq.outputs.cache-hit != 'true'
         run: |
-          wget https://github.com/mikefarah/yq/releases/download/v$YQ_VERSION/yq_linux_amd64.tar.gz -O - |\
-          tar xz && mv yq_linux_amd64 ${{ github.workspace }}/yq
+          wget https://github.com/mikefarah/yq/releases/download/v$YQ_VERSION/yq_linux_amd64.tar.gz -O yq.tar.gz
+          tar -xzf yq.tar.gz
+          mv yq_linux_amd64 ${{ github.workspace }}/yq
+          chmod +x ${{ github.workspace }}/yq
 
       - name: Save yq executable to cache
         if: steps.cache-yq.outputs.cache-hit != 'true'
-        uses: actions/cache@v4
+        uses: actions/cache/save@v4
         with:
           key: yq-${{ env.YQ_VERSION }}
           path: ${{ github.workspace }}/yq
-
+          
       - name: Get yamllint from cache
         id: cache-yamllint
         uses: actions/cache@v4
@@ -71,52 +76,190 @@ jobs:
           key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.YAMLLINT_VERSION }}
           restore-keys: |
             pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
-
+    
       - name: Install yamllint
         if: steps.cache-yamllint.outputs.cache-hit != 'true'
-        run: pip install yamllint==${{ env.YAMLLINT_VERSION }}
+        run: pip install --cache-dir ~/.cache/pip --upgrade yamllint==${{ env.YAMLLINT_VERSION }}
+
+      - name: Validate YAML with yamllint
+        run: |
+          echo "Validating ${{ matrix.file }} with yamllint..."
+          yamllint -c yamllint-config.yamllint ${{ matrix.file }}
 
       - name: Validate YAML syntax
         env:
           PATH: ${{ github.workspace }}/yq:$PATH
         run: |
           file=${{ matrix.file }}
-          echo "Validating $file with yamllint..."
-          expected_keys="name enabled host port protocol routes tags"
-          yamllint -d "{extends: default, rules: {indentation: {spaces: 2}, key-ordering: {enabled: true, order: ['name', 'enabled', 'host', 'port', 'protocol', 'routes', 'tags']}}}" "$file" || {
-            echo "Error: File $file does not follow the expected key order."
-            echo "Expected: $expected_keys"
+          echo "Validating $file ymal syntax..."
+
+          export YQ_PATH=${{ github.workspace }}/yq
+
+          if [[ ! -f "${{ github.workspace }}/yq" ]]; then
+            echo "Error: yq executable not found at ${{ github.workspace }}/yq"
             exit 1
-          }
+          fi
 
-          expected_route_keys="name host protocols methods paths strip_path plugins"
-          yq -e '.services[].routes[] | keys | join(" ")' "$file" | while read -r route_keys; do
-            if [[ "$route_keys" != "$expected_route_keys" && "$route_keys" != "name host protocols paths strip_path plugins" ]]; then
-              echo "Error: Key order in routes[] of $file does not follow the expected key order."
-              echo "Expected: $expected_route_keys"
-              echo "Found:    $route_keys"
+          expected_initial_keys="name enabled host port"
+          expected_end_keys="routes tags"
+          $YQ_PATH -e '.services[] | keys | join(" ")' "$file" | while read -r found_keys; do
+            if [[ ! "$found_keys" =~ ^$expected_initial_keys ]]; then
+              echo "Error: File $file does not follow the expected initial key order."
+              echo "Expected (initial): $expected_initial_keys"
+              echo "Found:              $found_keys"
+              exit 1
+            fi
+
+            if [[ "$found_keys" =~ (tls_verify|ca_certificates) ]]; then
+              if [[ ! "$found_keys" =~ port.*(tls_verify|ca_certificates) ]]; then
+                echo "Error: File $file does not follow the expected optional key order."
+                echo "Optional keys (tls_verify, ca_certificates) must come after 'port'."
+                echo "Found:    $found_keys"
+                exit 1
+              fi
+            fi
+
+            if [[ ! "$found_keys" =~ (protocol) ]]; then
+              echo "Error: File $file does not has the expected keys."
+              echo "Expected:  protocol"
+              echo "Found:     $found_keys"
+              exit 1
+            fi
+
+            if [[ "$found_keys" =~ (plugins) ]]; then
+              if [[ ! "$found_keys" =~ protocol.*(plugins) ]]; then
+                echo "Error: File $file does not follow the expected key order."
+                echo "key 'plugins' must come after 'protocol'."
+                echo "Found:    $found_keys"
+                exit 1
+              fi
+
+              if [[ ! "$found_keys" =~ plugins.*routes ]]; then
+                echo "Error: File $file does not follow the expected key order."
+                echo "Key 'plugins' must come before 'routes'."
+                echo "Found:    $found_keys"
+                exit 1
+              fi
+
+              expected_plugin_keys=("name" "enabled" "protocols" "config")
+              $YQ_PATH -e '.services[].plugins[] | keys | join(" ")' "$file" | while read -r plugin_keys; do
+                found_keys=($plugin_keys)
+
+                if [[ "${found_keys[*]}" != "${expected_plugin_keys[*]}" ]]; then
+                  echo "Error: Key order in plugins[] inside 'services' of $file does not follow the expected key order."
+                  echo "Expected: ${expected_plugin_keys[*]}"
+                  echo "Found:    ${found_keys[*]}"
+                  exit 1
+                fi
+              done
+
+              plugins_protocols=$($YQ_PATH eval '.services[].plugins[].protocols[]' "$file")
+              invalid_plugins_protocols=false
+
+              for protocol in $plugins_protocols; do
+                if [[ "$protocol" != "http" ]]; then
+                  invalid_plugins_protocols=true
+                  break
+                fi
+              done
+
+              if [[ "$invalid_plugins_protocols" == true ]]; then
+                echo "Error: Invalid plugins protocol inside 'services' in $file: Expected 'http' but got '$plugins_protocols'"
+                exit 1
+              fi
+            fi
+
+            if [[ ! "$found_keys" =~ $expected_end_keys$ ]]; then
+              echo "Error: File $file does not follow the expected end key order."
+              echo "Expected (end): $expected_end_keys"
+              echo "Found:          $found_keys"
               exit 1
             fi
           done
 
-          expected_plugin_keys="name enabled protocols config"
-          yq -e '.services[].routes[].plugins[] | keys | join(" ")' "$file" | while read -r plugin_keys; do
-            if [[ "$plugin_keys" != "$expected_plugin_keys" ]]; then
-              echo "Error: Key order in plugins[] of $file does not follow the expected key order."
-              echo "Expected: $expected_plugin_keys"
-              echo "Found:    $plugin_keys"
+          EXPECTED_KEYS=("name" "hosts" "protocols" "methods" "paths")
+
+          while IFS= read -r route_keys; do
+            found_keys=($route_keys)
+            
+            last_index=-1
+            for key in "${EXPECTED_KEYS[@]}"; do
+              for i in "${!found_keys[@]}"; do
+                if [[ "${found_keys[i]}" == "$key" ]]; then
+                  if [[ $i -lt $last_index ]]; then
+                    echo "Error: Key order in routes[] of $FILE does not follow the expected sequence."
+                    echo "Expected order: ${EXPECTED_KEYS[*]}"
+                    echo "Found order:    ${found_keys[*]}"
+                    exit 1
+                  fi
+                  last_index=$i
+                  break
+                fi
+              done
+            done
+            
+          done < <(yq -e '.services[].routes[] | keys | join(" ")' "$file")
+
+          # expected_route_keys=("name" "hosts" "protocols" "methods" "paths")
+          # $YQ_PATH -e '.services[].routes[] | keys | join(" ")' "$file" | while read -r route_keys; do
+          #   found_keys=($route_keys)
+
+          #   found_required_keys=()
+          #   for key in "${expected_route_keys[@]}"; do
+          #     if [[ " ${found_keys[*]} " == *" $key "* ]]; then
+          #       found_required_keys+=("$key")
+          #     fi
+          #   done
+
+          #   found_required_keys_str="${found_required_keys[*]}"
+          #   expected_route_keys_str="${expected_route_keys[*]}"
+
+          #   if [[ "$found_required_keys_str" != "$expected_route_keys_str" ]]; then
+          #     echo "Error: Key order in routes[] of $file does not follow the expected key order."
+          #     echo "Expected: $expected_route_keys_str"
+          #     echo "Found:    $found_required_keys_str"
+          #     exit 1
+          #   fi
+          # done
+
+          expected_plugin_keys=("name" "enabled" "protocols" "config")
+          $YQ_PATH -e '.services[].routes[].plugins[] | keys | join(" ")' "$file" | while read -r plugin_keys; do
+            found_keys=($plugin_keys)
+
+            if [[ "${found_keys[*]}" != "${expected_plugin_keys[*]}" ]]; then
+              echo "Error: Key order in plugins[] inside 'routes' of $file does not follow the expected key order."
+              echo "Expected: ${expected_plugin_keys[*]}"
+              echo "Found:    ${found_keys[*]}"
               exit 1
             fi
           done
 
-          routes_protocols=$(yq eval '.services[].routes[].protocols[]' "$file" | sort -u)
-          if [[ "$routes_protocols" != "http" ]]; then
+          routes_protocols=$($YQ_PATH eval '.services[].routes[].protocols[]' "$file")
+          invalid_routes_protocols=false
+
+          for protocol in $routes_protocols; do
+            if [[ "$protocol" != "http" ]]; then
+              invalid_routes_protocols=true
+              break
+            fi
+          done
+
+          if [[ "$invalid_routes_protocols" == true ]]; then
             echo "Error: Invalid routes protocol in $file: Expected 'http' but got '$routes_protocols'"
             exit 1
           fi
 
-          plugins_protocols=$(yq eval '.services[].routes[].plugins[].protocols[]' "$file" | sort -u)
-          if [[ "$plugins_protocols" != "http" ]]; then
-            echo "Error: Invalid plugins protocol in $file: Expected 'http' but got '$plugins_protocols'"
+          plugins_protocols=$($YQ_PATH eval '.services[].routes[].plugins[].protocols[]' "$file")
+          invalid_plugins_protocols=false
+
+          for protocol in $plugins_protocols; do
+            if [[ "$protocol" != "http" ]]; then
+              invalid_plugins_protocols=true
+              break
+            fi
+          done
+
+          if [[ "$invalid_plugins_protocols" == true ]]; then
+            echo "Error: Invalid plugins protocol inside 'routes' in $file: Expected 'http' but got '$plugins_protocols'"
             exit 1
           fi
